#!/bin/bash

cat <<EOF
To continue the installation, set now the config.toml file.
Read more about it at https://docs.gitlab.com/runner/install/autoscaling.html#configure-gitlab-runner

Configure [runners.machine] specifically.

You can hide this message on the next connection by deleting the $0 file.
EOF
